name: JSON
on:
  push:
    branches:
      - main
    paths:
      - "**.json"
  pull_request:
    paths:
      - "**.json"
  workflow_dispatch:
jobs:
#  lint:
#    uses: parcelLab/ci/.github/workflows/json.yaml@v1.7.0
  json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - name: Lint JSON
        uses: actionsx/prettier@v3
        with:
          args: --check "**/*.json"