name: PR
on:
  pull_request:
    types:
    - opened
    - edited
    - ready_for_review
    - reopened
    - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.0.0
    - name: Checkout current git repository
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn install --immutable
    - name: Run Danger
      run: yarn danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN_OPEN_SOURCE }}
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR based on branch name
      if: github.event.action == 'opened'
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Label PR based on pushed file paths
      uses: actions/labeler@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/pr-path-labeler.yml
        sync-labels: false
