name: Publish
on:
  release:
    types:
    - published
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true
env:
  BOT_EMAIL: dev.bot@parcellab.com
  BOT_NAME: parcellab-dev-bot
  PACKAGE: eslint-config-parcellab
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current git repository
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn install --immutable
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.0.0
    - name: Load version
      id: load_version
      run: |
        if [ "$GITHUB_EVENT_NAME" = 'workflow_dispatch' ]
        then
          VERSION="${{ github.event.inputs.version }}"
        else
          if [ "$GITHUB_EVENT_NAME" = 'release' ]
          then
            TAG_NAME="${{ github.event.release.tag_name }}"
          else
            TAG_NAME="${{ github.ref }}"
          fi
          CLEAN_TAG=${TAG_NAME##*/}
          VERSION=${CLEAN_TAG//v}
        fi
        echo "::set-output name=version::$VERSION"
    - name: Publish NPM package
      uses: JS-DevTools/npm-publish@v1
      with:
        access: public
        package: ./package.json
        registry: https://npm.pkg.github.com
        tag: ${{ steps.load_version.outputs.version }}
        token: ${{ github.token }}
