name: Release
on:
  # Directly publish a new release manually
  workflow_dispatch:
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_release.yaml
    with:
      publish: true
    secrets: inherit
