name: Test
on:
  push:
    branches:
    - main
    paths:
    - "*.js"
  pull_request:
    paths:
    - "*.js"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.0.0
    - name: Checkout current git repository
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn install --immutable
    - name: Run lint
      id: yarn_lint
      run: yarn lint
    - name: Run test
      id: yarn_test
      run: yarn test
  draft-release:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      id: release-wizard
      uses: darioblanco/release-wizard@main
      with:
        draft: false
        token: ${{ github.token }}
        pushTag: true
