name: Test
on:
  push:
    branches:
    - main
    paths:
    - "**.js"
    - "**.ts"
  pull_request:
    paths:
    - "**.js"
    - "**.ts"
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/_js.yaml
  draft-release:
    if: github.ref == 'refs/heads/main'
    needs:
    - test
    uses: ./.github/workflows/_release.yaml
    secrets: inherit
